// ─── Static visual metadata for menu categories ──────────────────────
// Shared by MenuPage (real list) and PageSkeletons (loading fallback) so
// the skeleton renders the exact same colored cards as the live page.

export const CATEGORY_EMOJI: Record<string, string> = {
  'Кофе': '☕',
  'Чай': '🍵',
  'Лимонады': '🍋',
  'Напитки': '🥤',
  'Авторские напитки': '✨',
  'Выпечка': '🥐',
  'Десерты': '🍰',
  'Завтраки': '🍳',
  'Салаты': '🥗',
  'Супы': '🍜',
  'Горячие блюда': '🍖',
  'Паста': '🍝',
  'Пицца': '🍕',
  'Бургеры': '🍔',
  'Сэндвичи': '🥪',
  'Суши': '🍣',
  'Японские роллы': '🍱',
  'Закуски': '🥨',
  'Гарниры': '🍚',
  'Соусы': '🧈',
  'Фреши': '🧃',
  'Смузи': '🥤',
  'Молочные коктейли': '🥛',
  'Детское меню': '👶',
  'Бизнес-ланчи': '💼',
  'Вегетарианское меню': '🥬',
  'Мороженое': '🍦',
  'Блины и панкейки': '🥞',
  'Стейки': '🥩',
  'Гриль и мангал': '🔥',
  'Боулы и Поке': '🥣',
  'Морепродукты': '🦐',
  'WOK': '🥘',
  'Шаурма и Донеры': '🌯',
  'Хот-доги': '🌭',
  'Пироги': '🥧',
  'Сеты': '🍱',
  'Сезонное меню': '🌸',
  'Алкогольные коктейли': '🍸',
  'Соки и Воды': '🧊',
};

// Categories with DUK images (image overrides emoji)
export const CATEGORY_IMAGE: Record<string, string> = {
  'Курица':         '/category_images/cat_chicken_1781168830514-removebg-preview.webp',
  'Напитки':        '/category_images/cat_drinks_1781174228324-removebg-preview.webp',
  'Кимбап':         '/category_images/cat_kimbap_1781168876530-removebg-preview.webp',
  'Горячие блюда':  '/category_images/cat_main_dishes_1781168963104-removebg-preview.webp',
  'Лапша':          '/category_images/cat_noodles_1781169005744-removebg-preview.webp',
  'Пицца':          '/category_images/cat_pizza_1781168865515-removebg-preview.webp',
  'Гарниры':        '/category_images/cat_side_dishes_1781174239254-removebg-preview.webp',
  'Супы':           '/category_images/cat_soups_1781168889004-removebg-preview.webp',
  'Японские роллы':           '/category_images/cat_sushi_1781168847922-removebg-preview.webp',
  'Десерты':        '/category_images/cat_desserts_1781177166251-removebg-preview.webp',
  'Соусы':          '/category_images/cat_sauces_1781176696071-removebg-preview.webp',
  'Кофе':           '/category_images/cat_coffee_1781186991524-removebg-preview.webp',
  'Чай':            '/category_images/cat_tea_1781186983122-removebg-preview.webp',
  'Лимонады':       '/category_images/cat_lemonades_white-removebg-preview.webp',
  'Молочные коктейли': '/category_images/cat_milkshakes_white-removebg-preview.webp',
  'Смузи':          '/category_images/cat_smoothies_white-removebg-preview.webp',
};

// Clean distinct colors for each DUK category
export const CATEGORY_COLOR: Record<string, string> = {
  'Пицца':          '#E89040',
  'Японские роллы':           '#5090E0',
  'Курица':         '#E0B040',
  'Кимбап':         '#40C840',
  'Горячие блюда':  '#E04868',
  'Лапша':          '#B8D848',
  'Гарниры':        '#8858D0',
  'Супы':           '#30B8B0',
  'Напитки':        '#4888E8',
  'Десерты':        '#E048A0',
  'Соусы':          '#C88840',
  'Кофе':           '#A06048',
  'Чай':            '#50B050',
  'Лимонады':       '#F0D040',
  'Молочные коктейли': '#D0B8E8',
  'Смузи':          '#F06060',
};
