CREATE TABLE IF NOT EXISTS public.faq (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    question_ru text NOT NULL,
    question_en text NOT NULL,
    question_kg text NOT NULL,
    answer_ru text NOT NULL,
    answer_en text NOT NULL,
    answer_kg text NOT NULL,
    order_index integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.faq ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on faq" ON public.faq;
CREATE POLICY "Allow public read access on faq" ON public.faq FOR SELECT USING (true);

INSERT INTO public.faq (question_ru, question_en, question_kg, answer_ru, answer_en, answer_kg, order_index) VALUES
('Как копить баллы?', 'How to earn points?', 'Упайларды кантип чогултуу керек?', 'Вы получаете баллы за каждую покупку. Просто покажите ваш QR-код баристе перед оплатой заказа. 1 балл = 1 сом.', 'You earn points for every purchase. Just show your QR code to the barista before paying. 1 point = 1 som.', 'Ар бир сатып алуу үчүн упай аласыз. Төлөөдөн мурун баристага QR-кодуңузду көрсөтүңүз. 1 упай = 1 сом.', 1),
('Как повысить уровень?', 'How to level up?', 'Деңгээлди кантип көтөрүү керек?', 'В нашей программе лояльности 4 уровня: Любитель (кэшбек 3%, 0-100 визитов), Ценитель (5%, 100-500), Знаток (7%, 500-1000) и Гурман (10%, 1000+). Ваш уровень повышается автоматически в зависимости от количества ваших визитов в кофейню. Чем чаще вы нас посещаете, тем выше ваш кэшбек!', 'Our loyalty program has 4 levels: Lover (3% cashback, 0-100 visits), Connoisseur (5%, 100-500), Expert (7%, 500-1000), and Gourmet (10%, 1000+). Your level increases automatically based on the number of visits to the cafe. The more often you visit us, the higher your cashback!', 'Биздин лоялдуулук программабызда 4 деңгээл бар: Сүйүүчү (кэшбек 3%, 0-100 сапар), Баалоочу (5%, 100-500), Билгич (7%, 500-1000) жана Гурман (10%, 1000+). Сиздин деңгээлиңиз кофеканага келген сапарларыңыздын санына жараша автоматтык түрдө жогорулайт. Бизге канчалык көп келсеңиз, кэшбекиңиз ошончолук жогору!', 2),
('Как сделать заказ?', 'How to place an order?', 'Буйрутманы кантип жасоо керек?', 'В данный момент функция предварительного заказа находится в разработке. Вы можете ознакомиться с меню в приложении и сделать заказ лично в любой из наших кофеен.', 'The pre-order feature is currently under development. You can browse the menu in the app and place an order in person at any of our cafes.', 'Учурда алдын ала буйрутма берүү функциясы иштелип жатат. Тиркемеде меню менен таанышып, биздин каалаган кофеканабызда өзүңүз буйрутма бере аласыз.', 3),
('Где посмотреть адреса кофеен?', 'Where to find cafe addresses?', 'Кофеканалардын даректерин кайдан көрүүгө болот?', 'Все адреса, графики работы и маршруты к нашим кофейням вы можете найти в разделе "Филиалы" на главном экране.', 'All addresses, working hours, and routes to our cafes can be found in the "Branches" section on the main screen.', 'Бардык даректерди, иш графиктерин жана биздин кофеканаларга маршруттарды башкы экрандагы "Филиалдар" бөлүмүнөн таба аласыз.', 4),
('Как оставить отзыв?', 'How to leave a review?', 'Пикирди кантип калтыруу керек?', 'Вы можете оставить отзыв на главной странице в разделе "Отзывы". Просто нажмите кнопку "Оставить отзыв" и поделитесь вашими впечатлениями.', 'You can leave a review on the main page in the "Reviews" section. Just tap "Leave a review" and share your impressions.', 'Сиз башкы беттеги "Пикирлер" бөлүмүндө пикир калтыра аласыз. Жөн гана "Пикир калтыруу" баскычын басып, таасирлериңиз менен бөлүшүңүз.', 5),
('Могу ли я удалить аккаунт?', 'Can I delete my account?', 'Аккаунтумду өчүрө аламбы?', 'Да, вы можете удалить свой аккаунт. Для этого напишите в нашу службу поддержки через раздел "Настройки и помощь", и мы удалим ваши данные в течение 30 дней.', 'Yes, you can delete your account. To do this, write to our support team through the "Settings & Help" section, and we will delete your data within 30 days.', 'Ооба, сиз аккаунтуңузду өчүрө аласыз. Бул үчүн "Жөндөөлөр жана жардам" бөлүмү аркылуу биздин колдоо кызматыбызга жазыңыз, биз сиздин маалыматтарыңызды 30 күндүн ичинде өчүрөбүз.', 6);

CREATE TABLE IF NOT EXISTS public.about_sections (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    icon text,
    title_ru text NOT NULL,
    title_en text NOT NULL,
    title_kg text NOT NULL,
    content_ru text NOT NULL,
    content_en text NOT NULL,
    content_kg text NOT NULL,
    order_index integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.about_sections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on about_sections" ON public.about_sections;
CREATE POLICY "Allow public read access on about_sections" ON public.about_sections FOR SELECT USING (true);

INSERT INTO public.about_sections (icon, title_ru, title_en, title_kg, content_ru, content_en, content_kg, order_index) VALUES
('📖', 'Наша история', 'Our story', 'Биздин тарых', 'Всё началось с мечты — создать место, где каждый глоток кофе рассказывает историю. Основанная в 2020 году, наша кофейня выросла из маленького киоска в сеть уютных пространств по всему городу. Мы начинали с одной кофемашины и безграничной любви к своему делу, а сегодня нас знают и любят тысячи гостей. Каждый день мы просыпаемся с мыслью о том, как сделать ваш кофе ещё вкуснее, а атмосферу — ещё теплее. Это не просто бизнес, это наша страсть, которой мы делимся с вами.', 'It all started with a dream — to create a place where every sip of coffee tells a story. Founded in 2020, our coffee shop has grown from a small kiosk into a network of cozy spaces throughout the city. We started with one coffee machine and boundless love for our craft, and today thousands of guests know and love us. Every day we wake up thinking about how to make your coffee even tastier and the atmosphere even warmer. This is not just a business, it''s our passion that we share with you.', 'Баары бир кыялдан башталган — кофенин ар бир ууртамы окуяны баяндаган жайды түзүү. 2020-жылы негизделген биздин кофекана кичинекей дүңгүрчөдөн шаар боюнча жайлуу мейкиндиктердин тармагына айланды. Биз бир кофе машинасы жана өз ишибизге чексиз сүйүү менен баштаганбыз, ал эми бүгүн миңдеген коноктор бизди билишет жана жакшы көрүшөт. Күн сайын кофеңизди дагы даамдуу, атмосфераны дагы жылуу кылуу жөнүндө ойлонуп ойгонобуз. Бул жөн гана бизнес эмес, бул биздин сиз менен бөлүшкөн кумарыбыз.', 1),
('☕', 'Наш кофе', 'Our coffee', 'Биздин кофе', 'Мы работаем только с премиальной арабикой из Бразилии, Эфиопии и Колумбии. Каждое зерно проходит тройной контроль качества: на плантации, при транспортировке и перед обжаркой. Мы обжариваем кофе малыми партиями, чтобы сохранить всю глубину вкуса и аромата — от ярких цитрусовых нот до бархатистых шоколадных оттенков.', 'We work only with premium Arabica from Brazil, Ethiopia, and Colombia. Each bean undergoes triple quality control: on the plantation, during transportation, and before roasting. We roast coffee in small batches to preserve the full depth of flavor and aroma — from bright citrus notes to velvety chocolate shades.', 'Биз Бразилия, Эфиопия жана Колумбиядан келген премиум Арабика менен гана иштейбиз. Ар бир дан үч эсе сапат көзөмөлүнөн өтөт: плантацияда, ташуу учурунда жана кууруу алдында. Даамы менен жытынын толук тереңдигин — ачык цитрус ноталарынан баркыт шоколад түстөрүнө чейин сактоо үчүн кофени кичинекей партиялар менен куурабыз.', 2),
('💚', 'Наша философия', 'Our philosophy', 'Биздин философия', 'Кофе — это больше, чем напиток. Это ритуал, который объединяет людей, дает минуты спокойствия в суете дня и становится поводом для искренних разговоров. Мы создаём пространство, где комфортно каждому: студенту с ноутбуком, деловому партнёру на встрече или друзьям за воскресным бранчем. Уважение к гостю, забота о качестве и внимание к деталям — вот три принципа, на которых строится каждый наш день.', 'Coffee is more than just a drink. It is a ritual that brings people together, gives moments of peace in the hustle of the day, and becomes a reason for sincere conversations. We create a space where everyone feels comfortable: a student with a laptop, a business partner at a meeting, or friends at a Sunday brunch. Respect for the guest, care for quality, and attention to detail — these are the three principles on which every day of ours is built.', 'Кофе — бул суусундуктан да көп нерсе. Бул адамдарды бириктирген, күндүн ызы-чуусунда тынчтык мүнөттөрүн берген жана чын жүрөктөн сүйлөшүүлөргө себеп болгон ырым. Биз ар бир адамга ыңгайлуу болгон мейкиндикти түзөбүз: ноутбук менен студентке, жолугушуудагы бизнес өнөктөшкө же жекшемби күнкү эртең мененки тамакта досторго. Конокко урматтоо, сапатка кам көрүү жана майда-чүйдөсүнө чейин көңүл буруу — бул биздин ар бир күнүбүз курулган үч принцип.', 3),
('⭐', 'Почему выбирают нас', 'Why choose us', 'Эмне үчүн бизди тандашат', 'Свежая обжарка каждую неделю, авторские напитки от чемпионов бариста, уютный интерьер с панорамными окнами и бесплатный Wi-Fi. Мы помним ваше имя и любимый напиток уже со второго визита. Бонусная программа позволяет копить баллы и получать подарки. А ещё у нас проходят кофейные мастер-классы, дегустации и джем-сейшены по выходным.', 'Fresh roasting every week, signature drinks from champion baristas, cozy interior with panoramic windows and free Wi-Fi. We remember your name and favorite drink from your second visit. Our bonus program allows you to accumulate points and receive gifts. We also host coffee masterclasses, tastings, and jam sessions on weekends.', 'Ар жума сайын жаңы кууруу, чемпион баристалардан автордук суусундуктар, панорамалык терезелери менен жайлуу интерьер жана акысыз Wi-Fi. Биз сиздин атыңызды жана сүйүктүү суусундугуңузду экинчи сапарыңыздан эле эстейбиз. Бонустук программа упайларды чогултууга жана белектерди алууга мүмкүндүк берет. Ошондой эле дем алыш күндөрү кофе мастер-класстары, дегустациялар жана джем-сешндер өткөрүлөт.', 4);

-- Also insert intro text into app_settings
INSERT INTO public.app_settings (settings_key, settings_value) VALUES 
('about_cafe_intro_ru', 'Cafe — это уютная кофейня в самом сердце города, где каждый гость становится частью нашей кофейной семьи. Мы варим кофе из отборных зёрен арабики, обжаренных с любовью и заботой. Наши бариста — настоящие мастера своего дела, которые знают, как превратить обычную чашку кофе в маленькое произведение искусства. Мы верим, что хороший кофе — это не просто напиток, а целая культура, объединяющая людей. Приходите к нам за настроением, оставайтесь за вкусом!'),
('about_cafe_intro_en', 'Cafe is a cozy coffee shop in the heart of the city, where every guest becomes part of our coffee family. We brew coffee from selected Arabica beans, roasted with love and care. Our baristas are true masters who know how to turn an ordinary cup of coffee into a small work of art. We believe that good coffee is not just a drink, but a whole culture that brings people together. Come to us for the mood, stay for the taste!'),
('about_cafe_intro_kg', 'Cafe — бул шаардын жүрөгүндөгү жайлуу кофе дүкөнү, мында ар бир конок биздин кофе үй-бүлөбүздүн бир бөлүгү болуп калат. Биз сүйүү жана камкордук менен куурулган тандалган Арабика данынан кофе демдейбиз. Биздин баристалар — кадимки чөйчөк кофени кичинекей искусство чыгармасына айландыра билген чыныгы чеберлер. Жакшы кофе — бул жөн гана суусундук эмес, адамдарды бириктирген бүтүндөй маданият деп ишенебиз. Маанай үчүн бизге келиңиз, даамы үчүн калыңыз!')
ON CONFLICT (settings_key) DO UPDATE SET settings_value = EXCLUDED.settings_value;
